### PR TITLE
Validation: creating bbr-requirements.yaml and modifying bbr-stories.yaml

### PR DESCRIPTION
**Pull request by seth127**
This is an update to our validation process. Where we previously linked user stories directly to tests that confirm the associated functionality, going forward we will link user stories to requirements that need to be met to satisfy the story, and then link those requirements to tests that confirm them.

### CODE REVIEW

**Comment by seth127** [comment]
@kyleam @barrettk @rymarinelli tagging you all for visibility here. I put @barrettk on to review this, but any of you could. Probably pull this and run `build-validation-docs.R` to make sure it works for you and builds docs that look good.

To be clear, this is only to generate the new requirements YAML file. We will be manually adding to that file going forward, _not_ pulling the descriptions from test names as we do here.

**Comment by barrettk** [comment]
@seth127 the validation docs didnt build for me. I didnt see a new version of mrgvalprep to be installed via pkgr. Is there anything else I need to do before generating the docs?
image
image

**Comment by kyleam** [comment]
@barrettk You'll need to install mrgvalprep from its latest develop branch to get the fix from https://github.com/metrumresearchgroup/mrgvalprep/pull/43

**Review by barrettk — APPROVED** [review]
Looks good. I like the idea of making all the requirement ID's based on the previous testID, as that makes it easier to assume there are no duplicates. Validation docs built after pulling in the latest mrgvalprep changes

**Pull request merged**
