### PR TITLE
DO NOT MERGE: bbr Stan modeling ALPHA release

### PR DESCRIPTION
**Pull request by seth127**
# bbr_stan_alpha
The intention of this branch is to begin implementing support for Stan modeling with `bbr`. While this code should all be tested and working, **the function names and API are considered experimental and may change with new releases.** The plan is to merge this functionality into `bbr` proper once this has stabilized.

All releases tagged `1.1.0.9xxx` refer to "alpha" releases cut from the `bbr_stan_alpha` branch.

### CODE REVIEW

**Comment by kyleam** [comment]
I've pushed an update to this PR that

  * merges in `develop` and resolves the conflicts

    1db55dde6d00e40f4a6a31d0f5e5e0f5115c38e1

  * reverts the default value change for the `.inherit_tags` argument of `copy_model_from`

    This was necessary to resolve three test failures, and I think it's a good idea in general to not bundle that default change with this stan branch.

    7e00a778c72345f1ca4d62c234bf170169933b73

If for any reason we want to restore this branch to its state before the merge, we can reset to 7deb4e442ef15230b500494a958e2d8bfd94fe4d.

<details>
<summary>tests</summary>

```
ip-10-128-2-59:bbr-stan$ git show --oneline -s
7e00a77 (HEAD -> bbr_stan_alpha) Revert "feat: changed copy_model_from(.inherit_tags) to default to TRUE"

ip-10-128-2-59:bbr-stan$ Rscript -e 'devtools::test()'
ℹ Loading bbr
ℹ Testing bbr
✔ | F W S  OK | Context
✔ |         6 | adding files to Stan models [0.1s]
✔ |        21 | bbr exec functions [0.5s]
✔ |         6 | building data objects for modeling [0.6s]
✔ |         6 | checking Stan model integrity
✔ |        20 | checking if models are up to date [1.1s]
✔ |         9 | Collapse columns to string representation [0.4s]
✔ |        81 | Constructing config log from bbi_config.json [1.7s]
✔ |        41 | Copying model objects [0.4s]
✔ |         6 | copy-model-helpers [0.3s]
✔ |        34 | cov-cor [0.6s]
✔ |        35 | Extract model paths from based_on fields [1.1s]
✔ |        54 | Build paths from model object [0.3s]
✔ |        16 | model_diff() comparing models [1.0s]
✔ |        19 | Test bbi summary on multiple models [0.6s]
✔ |       101 | Test bbi summary functions [1.1s]
✔ |        67 | Modify attributes of model object [0.4s]
✔ |        29 | Testing function to create or read in model object [0.1s]
✔ |        28 | nm-file [0.2s]
✔ |        27 | nm-join [0.7s]
✔ |        20 | nm-tables [0.2s]
✔ |        30 | Test bbi batch parameter estimate functions [4.8s]
✔ |         6 | Test param_estimates functions [0.4s]
✔ |        39 | test parsing labels for parameter table [1.5s]
✔ |        38 | testing print methods for bbi objects [3.7s]
✔ |         5 | read_bbi_path() helper function
✔ |         6 | reading fit model objects from disk [0.3s]
✔ |        50 | Reading NONMEM output files into R [0.6s]
✔ |        40 | Constructing run log from model yaml [1.0s]
✔ |        10 | submit_model(.dry_run=T)
✔ |        14 | submit_models(.dry_run=T) [0.2s]
✔ |        75 | Test creating summary logs [5.7s]
✔ |         9 | Comparing tags between models [0.2s]
✔ |        20 | test_threads(.dry_run=T) [3.7s]
✔ |         7 | test-use-bbi [3.6s]
✔ |        29 | Utility functions for building args, etc. [0.1s]
✔ |        42 | testing a composable workflow and running bbi [85.2s]
✔ |        15 | testing submitting Stan models [243.2s]

══ Results ═══════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════
Duration: 366.6 s

[ FAIL 0 | WARN 0 | SKIP 0 | PASS 1061 ]
```

</details>


---

`vignettes/getting-started-stan.Rmd` mostly works for me at that point.  The main issue I ran into is that `inst/model/stan/fxa/fxa-output/fit.RDS` hard codes the (absolute file paths) of the original trace files, but these of course do not exist for me (both because they are not tracked in the repo and because they are absolute paths).

Just in terms of checking functionality, I can instead use the model I just sampled from:

```diff
diff --git a/vignettes/getting-started-stan.Rmd b/vignettes/getting-started-stan.Rmd
index d6357a8..d9b4039 100644
--- a/vignettes/getting-started-stan.Rmd
+++ b/vignettes/getting-started-stan.Rmd
@@ -191,7 +191,7 @@ fxa_res <- fxaInc %>%

 {r, echo = FALSE}
 # load the res object
-fxa_res <- read_fit_model(fxa)
+fxa_res <- read_fit_model(fxaInc)

 # load the fake posteriors
 fake_summary_df <- readRDS(system.file("vignette-fakes", "cmdstanr-summary-tibble.RDS", package = "bbr"))
@@ -248,7 +248,7 @@ fake_summary_df %>%
 The `submit_model()` call automatically saves this fit object to disk as well. You can pass either a path or model object to `bbr::read_fit_model()` and it will re-load the `CmdStanMCMC` object into memory.

 {r}
-new_res <- read_fit_model(file.path(MODEL_DIR, "fxa"))
+new_res <- read_fit_model(file.path(MODEL_DIR, "fxaInc"))
 new_res$sampler_diagnostics() %>% str()

@@ -258,7 +258,7 @@ new_res$sampler_diagnostics() %>% str()
 We have **not yet implemented** `bbr::model_summary()` for `bbi_stan_model` objects. This is a work in progress, but until it is done, `model_summary()` currently returns the same fit object that was just discussed, and warns you to that effect.

 {r model_summary}
-sum1 <- fxa %>% model_summary()
+sum1 <- fxaInc %>% model_summary()
 class(sum1)
```

(That diff drops the Rmarkdown ticks to avoid confusing GitHub's rendering.)

I held off on making any changes in that direction because 1) presumably the mock vignette output uses the fxa model rather than fxaInc and 2) there's still the more important conceptual issue the absolute paths to the output files being hard coded in the rds.

**Comment by kyleam** [comment]
Since the last sync with `main`, quite a few conflicts have popped up (with star support being the only one where the resolution is not just "take both sides").  I've pushed a merge that resolves these conflicts.  (The plan is to split move the functionality added by this branch into its own repo, but in the process it will be helpful to have this branch be as up to date as possible.)

It also tightens the condition added in 03b78467 to [a avoid the Drone failure](https://github-drone.metrumrg.com/metrumresearchgroup/bbr/2706/1/4).  @seth127, let me know if anything looks off there (9a7fd010).

**Comment by seth127** [comment]
Thanks @kyleam . I don't see any problem with that. We may want to re-assess this pattern at some point. As I recall, it had to do with this being a working doc that folks were trying to play with to test out the new functionality and share for feedback, hence the need for interactive and knitting, as opposed to a more traditional vignette. At some point that likely won't be the case anymore.

Anyway, for now I agree: let's just get it passing.

**Comment by kyleam** [comment]
Just a note that this PR was auto-merged with the merge of gh-543.  gh-543 built on top of the commits in this PR and includes the tip commit (0340acc5) of this PR.

The diff in gh-543 shows the changes against `main`, but the substantial changes (in terms of the bbr.bayes split) from this PR and gh-543 mostly come from this set: https://github.com/metrumresearchgroup/bbr/compare/13e0f79c424db1408afcb7ed3ba89cfeae312b34...5b3e504d894407a878e317d90837139f5c623548

**Pull request merged**
